/* ── Edge Fallback Protocols ──────────────────────────────────
   Pre-computed crisis decisions used when cloud AI is offline.
*/

export const EDGE_PROTOCOLS = {
  fire: {
    detection: `EDGE PROTOCOL ACTIVE — Fire signature detected.
Initiating standard fire emergency protocol.

LOCATION: Floor 3 East Wing, Kitchen area.
CLASSIFICATION: Kitchen fire, probable.
SEVERITY: CRITICAL (8/10).
CONFIDENCE: 91 % based on thermal + smoke + motion correlation.

ACTIVE SIGNALS:
• THERM-01 — 67 °C hotspot
• SMK-F301 — density 0.78
• MOT-F301 — surge 14 persons in corridor C

Reasoning: thermal anomaly + smoke confirmation + crowd flux match
the cached "kitchen fire — east wing" decision tree exactly.`,

    coordination: `EDGE COORDINATION PROTOCOL:

FLOOR 3: Evacuate via Stairwell A immediately. Avoid east corridor.
FLOORS 1–2: Orderly evacuation via main stairwell.
LOBBY: Clear to street, move 50 m from building.

STAFF ASSIGNMENTS:
• Marcus Reid — Security: Floor 3 — Direct guests to Stairwell A
• Troy Vasquez — Security: Floor 3 — Block east corridor access
• Priya Mehta — Medical: Lobby — Stage triage point at front entrance
• Lena Fischer — Medical: Floor 2 — Sweep rooms and assist mobility-impaired
• James Okafor — Manager: Lobby — Liaise with arriving fire department
• Sofia Reyes — Manager: Floor 4 — Lead F4 precautionary descent
• Ben Hartley — Concierge: Lobby — Account for VIP guests
• Clara Novak — Housekeeping: Floor 3 — Final sweep of west wing rooms

ZONE COMMUNICATIONS:
• Floor 3 East: "Evacuate now via Stairwell A. Do not use elevators."
• Floor 3 West: "Walk calmly to Stairwell A. Hotel staff are guiding you."
• Floors 1 & 2: "Please use the central stairwell. Move calmly to the lobby."
• Lobby: "Please exit through the main entrance and move away from the building."

Estimated evacuation: 4 m 30 s.`,

    bridge: JSON.stringify({
      incidentType: 'fire',
      severity: 8,
      location: 'Floor 3, East Wing, Kitchen Area',
      personsAffected: 23,
      accessRoute: 'Main entrance, Stairwell A clear',
      timestamp: new Date().toISOString(),
      note: 'Generated by edge compute — cloud sync pending',
    }, null, 2),
  },

  crowdSurge: {
    detection: `EDGE PROTOCOL ACTIVE — Crowd surge signature detected.

LOCATION: Lobby, main entrance.
CLASSIFICATION: Crush risk from concurrent check-in + drill alarm.
SEVERITY: CRITICAL (8/10).
CONFIDENCE: 88 %.

ACTIVE SIGNALS:
• MOT-L01 — 74 persons in entrance zone
• CO2-L01 — 1800 ppm (ventilation insufficient)
• CCTV-Lobby — compression detected at main doors`,
    coordination: `EDGE COORDINATION PROTOCOL:

LOBBY: Open secondary side exits, divert flow.
FLOOR 1: Lock elevators, redirect upward overflow to south stairwell.

STAFF ASSIGNMENTS:
• Marcus Reid — Security: Lobby — Open side exits
• Dana Cho — Security: Floor 1 — Manage stairwell N congestion
• Priya Mehta — Medical: Lobby — Triage near concierge desk

ZONE COMMUNICATIONS:
• Lobby: "Please use side exits — main entrance temporarily closed."`,
    bridge: JSON.stringify({
      incidentType: 'crowd-surge',
      severity: 8,
      location: 'Lobby, main entrance',
      personsAffected: 74,
      accessRoute: 'Side exit B clear',
      timestamp: new Date().toISOString(),
      note: 'Generated by edge compute — cloud sync pending',
    }, null, 2),
  },
}

export function pickProtocol(scenarioName = '') {
  const lower = scenarioName.toLowerCase()
  if (lower.includes('crowd')) return EDGE_PROTOCOLS.crowdSurge
  return EDGE_PROTOCOLS.fire
}
